### ISSUE TITLE
Mag EAN onderdeel zijn van een identifier in het apparaat?

### ISSUE THREAD

**Issue by Laurentjg** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#34]
Privacyoverweging voor opwek en later: load.

**Comment by MiD4All** [comment]
Nee. 
Overigens verwacht ik dat je bedoeld met EAN de (of een) EAN die betrekking heeft op de aansluiting, een product of de leverancier.

De identifier van een apparaat kan niet (gedeeltelijk) gebaseerd zijn op een locatie, functie of gebruik.

Als met EAN bedoeld wordt de verwijzing naar de aansluiting kan EAN niet zomaar worden opgenomen. Zonder het nu verder uit zoeken of het niet anders zou kunnen zou ik willen voorkomen dat dergelijke gegevens überhaupt in het apparaten terechtkomen. (aanname privacy by design)

**Comment by Laurentjg** [comment]
Met EAN wordt inderdaad bedoeld de verwijzing naar de aansluiting. @MiD4All , ik kan helaas in je profiel niet wat je achtergrond / bedrijf is. Ik hou het issue openstaan tot 28 februari voor discussie.

**Comment by Sander3003** [comment]
In de huidige opzet wordt er geen EAN code uitgewisseld op de elektriciteitsproductie eenheden interface.

**Comment by Laurentjg** [comment]
Opmerking van Sander3003 is verder gemotiveerd in keuze "Geen privacy-gevoelige data in uitwisseling interface<->"centrale" systemen" in bijlage 3. Hiermee is issue gesloten.
